version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: markdown-it
    versions:
    - 12.0.4
    - 12.0.5
  - dependency-name: clean-css
    versions:
    - 5.0.1
    - 5.1.0
    - 5.1.1
  - dependency-name: markdown-it-anchor
    versions:
    - 7.0.1
    - 7.0.2
